### PR TITLE
enhance client, go lang server using writev

### PR DESCRIPTION
**Pull request by wheelcomplex**
go lang server must compiled by my shadow edition go with writev supported(https://github.com/wheelcomplex/go/commit/c724ea00112063cb84f308bdf7a3bfa6a398cb5b)

and work in linux x86_64 only.

### CODE REVIEW

**Comment by wheelcomplex** [comment]
in my ubuntu 15.04 x64, I7 4700HQ (1 cpus for all server)
with writev:
go lang server: Elasped time is 44.00 seconds, bandwidth 6238.00 MB/s
cpp server: Elasped time is 221.00 seconds, bandwidth 6956.71 MB/s

without writev+group write:
go lang server: Elasped time is 45.00 seconds, bandwidth 2823.80 MB/s
cpp server: Elasped time is 55.00 seconds, bandwidth 5467.31 MB/s

**Comment by winlinvip** [comment]
Seems the writev is:
1. When use write(p0, p1, ..., pN), the writev can avoid lots of syscall.
2. When use bigbuffer(p0, p1, ..., pN), writev(bigbuffer) can avoid memory copy.

I have profile it at https://github.com/golang/go/issues/13451#issuecomment-165712601
The private implementation of writev is https://github.com/winlinvip/go/pull/1/files

**Comment by wheelcomplex** [comment]
Thanks for your discovery, I have gave up this pull requests.

**Comment by winlinvip** [comment]
@wheelcomplex Will golang accept the proposal to support writev? Seems it's useful for server. :smiley_cat:

**Comment by wheelcomplex** [comment]
@winlinvip I do not know, I will keep it in my shadow edition for my selft :D

**Pull request closed without merging**
